# =============================================================================
# ESP32 CYD (Cheap Yellow Display) - Home Assistant Touch Panel
# =============================================================================
# 
# Project: Smart Home Control Panel for ESP32-2432S028R
# Device: 320x240 ILI9342 TFT Display with XPT2046 Touch Controller
# Purpose: Provides a touchscreen interface to control Home Assistant entities
#          and displays real-time sensor data (weather, temperature, humidity)
#
# Architecture:
#   - Main configuration: cyd_ha_refactored.yaml (this file)
#   - Secrets: secrets.yaml (WiFi, API keys, passwords)
#   - UI Resources: cyd_ha/common.yaml (fonts, colors, icons)
#   - Hardware: cyd_ha/hardware.yaml (SPI, touch, display, outputs)
#   - Sensors: cyd_ha/sensors.yaml (Home Assistant integrations)
#   - Controls: cyd_ha/buttons.yaml (touchscreen button definitions)
#   - Display: cyd_ha/display.yaml (UI rendering logic)
#
# Author: Refactored for maintainability and security
# Date: October 2025
# =============================================================================

# Substitutions - centralized for easier sharing/localization
substitutions: !include cyd_ha/substitutions.yaml

# =============================================================================
# Core ESPHome Configuration
# =============================================================================

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  comment: "ESP32 CYD Touch Panel for Home Assistant"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Logging Configuration
logger:
  level: INFO  # Options: NONE, ERROR, WARN, INFO, DEBUG, VERBOSE
  logs:
    sensor: WARN
    text_sensor: WARN

# Home Assistant API (encrypted connection)
api:
  encryption:
    key: !secret cyd_ha_api_encryption_key
  reboot_timeout: 15min

# Over-The-Air Updates (secured with password)
ota:
  - platform: esphome
    password: !secret cyd_ha_ota_password

# WiFi Configuration (credentials stored in secrets.yaml)
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Fast connection for better responsiveness
  fast_connect: true
  
  # Power saving disabled for stable touch response
  power_save_mode: none

  # Fallback Access Point (if WiFi fails)
  ap:
    ssid: !secret cyd_ha_ap_ssid
    password: !secret cyd_ha_ap_password

# Captive Portal (for WiFi setup via fallback AP)
captive_portal:

# =============================================================================
# Global Variables
# =============================================================================

globals:
  - id: show_return_page
    type: bool
    restore_value: no
    initial_value: "false"
  - id: menu_display_time
    type: unsigned long
    restore_value: no
    initial_value: "0"
  - id: current_page
    type: int
    restore_value: yes
    initial_value: "0"

# =============================================================================
# Time Synchronization
# =============================================================================

# Fetch time from Home Assistant for display
time:
  - platform: homeassistant
    id: esptime
    timezone: Europe/Paris

# =============================================================================
# Auto-return to main screen after 30 seconds
# =============================================================================

interval:
  - interval: 1s
    then:
      - lambda: |-
          if (id(show_return_page)) {
            // Check if 30 seconds have passed since menu was displayed
            if (millis() - id(menu_display_time) >= 30000) {
              id(show_return_page) = false;
            }
          }

# =============================================================================
# Modular Includes (organized configuration)
# =============================================================================

# UI Resources: Fonts, Colors, Icons
<<: !include cyd_ha/common.yaml

# Hardware: SPI, Touch, Display, Outputs, Lights
<<: !include cyd_ha/hardware.yaml

# Home Assistant Sensors Integration
<<: !include cyd_ha/sensors.yaml

# Touchscreen Button Definitions
binary_sensor: !include cyd_ha/buttons.yaml

# Display UI Rendering Logic (menu classique + pages défilantes)
<<: !include cyd_ha/display_pages.yaml