# =============================================================================
# Touchscreen Button Definitions
# =============================================================================
# List format for inclusion under `binary_sensor:`
# All services/entities are configured in substitutions.yaml.
# =============================================================================

# Button 1: Top Left
- platform: touchscreen
  name: Button 1
  x_min: 15
  x_max: 115
  y_min: 15
  y_max: 80
  on_press:
    then:
      - logger.log:
          level: INFO
          tag: touch
          format: "Button 1 pressed"
      - if:
          condition:
            lambda: 'return !id(show_return_page);'
          then:
            - globals.set:
                id: show_return_page
                value: !lambda "return !id(show_return_page);"
            - globals.set:
                id: menu_display_time
                value: !lambda "return millis();"
          else:
            - homeassistant.service:
                service: $btn1_service
                data:
                  entity_id: $btn1_entity
            - globals.set:
                id: menu_display_time
                value: !lambda "return millis();"

# Button 2: Top Right
- platform: touchscreen
  name: Button 2
  x_min: 125
  x_max: 225
  y_min: 15
  y_max: 80
  on_press:
    then:
      - logger.log:
          level: INFO
          tag: touch
          format: "Button 2 pressed"
      - if:
          condition:
            lambda: 'return !id(show_return_page);'
          then:
            - globals.set:
                id: show_return_page
                value: !lambda "return !id(show_return_page);"
            - globals.set:
                id: menu_display_time
                value: !lambda "return millis();"
          else:
            - homeassistant.service:
                service: $btn2_service
                data:
                  entity_id: $btn2_entity
            - globals.set:
                id: menu_display_time
                value: !lambda "return millis();"

# Button 3: Middle Left
- platform: touchscreen
  name: Button 3
  x_min: 15
  x_max: 115
  y_min: 90
  y_max: 155
  on_press:
    then:
      - logger.log:
          level: INFO
          tag: touch
          format: "Button 3 pressed"
      - if:
          condition:
            lambda: 'return !id(show_return_page);'
          then:
            - globals.set:
                id: show_return_page
                value: !lambda "return !id(show_return_page);"
            - globals.set:
                id: menu_display_time
                value: !lambda "return millis();"
          else:
            - homeassistant.service:
                service: $btn3_service
                data:
                  entity_id: $btn3_entity
            - globals.set:
                id: menu_display_time
                value: !lambda "return millis();"

# Button 4: Middle Right
- platform: touchscreen
  name: Button 4
  x_min: 125
  x_max: 225
  y_min: 90
  y_max: 155
  on_press:
    then:
      - logger.log:
          level: INFO
          tag: touch
          format: "Button 4 pressed"
      - if:
          condition:
            lambda: 'return !id(show_return_page);'
          then:
            - globals.set:
                id: show_return_page
                value: !lambda "return !id(show_return_page);"
            - globals.set:
                id: menu_display_time
                value: !lambda "return millis();"
          else:
            - homeassistant.service:
                service: $btn4_service
                data:
                  entity_id: $btn4_entity
            - globals.set:
                id: menu_display_time
                value: !lambda "return millis();"

# Button 5: Bottom Left
- platform: touchscreen
  name: Button 5
  x_min: 15
  x_max: 115
  y_min: 165
  y_max: 230
  on_press:
    then:
      - logger.log:
          level: INFO
          tag: touch
          format: "Button 5 pressed"
      - if:
          condition:
            lambda: 'return !id(show_return_page);'
          then:
            - globals.set:
                id: show_return_page
                value: !lambda "return !id(show_return_page);"
            - globals.set:
                id: menu_display_time
                value: !lambda "return millis();"
          else:
            - homeassistant.service:
                service: $btn5_service
                data:
                  entity_id: $btn5_entity
            - globals.set:
                id: menu_display_time
                value: !lambda "return millis();"

# Button 6: Bottom Middle
- platform: touchscreen
  name: Button 6
  x_min: 125
  x_max: 225
  y_min: 165
  y_max: 230
  on_press:
    then:
      - logger.log:
          level: INFO
          tag: touch
          format: "Button 6 pressed"
      - if:
          condition:
            lambda: 'return !id(show_return_page);'
          then:
            - globals.set:
                id: show_return_page
                value: !lambda "return !id(show_return_page);"
            - globals.set:
                id: menu_display_time
                value: !lambda "return millis();"
          else:
            - homeassistant.service:
                service: $btn6_service
                data:
                  entity_id: $btn6_entity
            - globals.set:
                id: menu_display_time
                value: !lambda "return millis();"

# Button 7: Lower Left
- platform: touchscreen
  name: Button 7
  x_min: 15
  x_max: 115
  y_min: 240
  y_max: 305
  on_press:
    then:
      - logger.log:
          level: INFO
          tag: touch
          format: "Button 7 pressed"
      - if:
          condition:
            lambda: 'return !id(show_return_page);'
          then:
            - globals.set:
                id: show_return_page
                value: !lambda "return !id(show_return_page);"
            - globals.set:
                id: menu_display_time
                value: !lambda "return millis();"
          else:
            - homeassistant.service:
                service: $btn7_service
                data:
                  entity_id: $btn7_entity
            - globals.set:
                id: menu_display_time
                value: !lambda "return millis();"

# Button 8: Lower Right (Return/Back)
- platform: touchscreen
  name: Button 8
  x_min: 125
  x_max: 225
  y_min: 240
  y_max: 305
  on_press:
    then:
      - logger.log:
          level: INFO
          tag: touch
          format: "Button 8 pressed"
      - if:
          condition:
            lambda: 'return !id(show_return_page);'
          then:
            # Opening menu - set timestamp for timeout
            - globals.set:
                id: menu_display_time
                value: !lambda "return millis();"
      - globals.set:
          id: show_return_page
          value: !lambda "return !id(show_return_page);"
