# Home Assistant Sensors Integration
# Imports sensor data from Home Assistant entities

# =============================
# Numeric Sensors (measurements)
# =============================
sensor:
  # ── Home (indoor sensors)
  - platform: homeassistant
    id: temp_int
    entity_id: $internal_temp_sensor
    internal: true
  - platform: homeassistant
    id: hum_int
    entity_id: $internal_humidity_sensor
    internal: true
  - platform: homeassistant
    id: int2_temp
    entity_id: $int2_temp_sensor
    internal: true
  - platform: homeassistant
    id: int2_hum
    entity_id: $int2_humidity_sensor
    internal: true
  # ── Outdoor (dedicated sensors)
  - platform: homeassistant
    id: temp_ext
    entity_id: $outside_temp_sensor
    internal: true
  
  # ── Weather — Probabilities
  - platform: homeassistant
    id: rainchance
    entity_id: $rain_chance
    internal: true
  - platform: homeassistant
    id: snowchance
    entity_id: $snow_chance
    internal: true
  - platform: homeassistant
    id: freezechance
    entity_id: $freeze_chance
    internal: true

  # ── Weather — Attributes from weather entity
  - platform: homeassistant
    id: wind_speed
    entity_id: ${weather_entity}
    attribute: wind_speed
    internal: true
  
  # Weather - Additional attributes
  - platform: homeassistant
    id: humidity_ext
    entity_id: ${weather_entity}
    attribute: humidity
    internal: true
  
  - platform: homeassistant
    id: pressure
    entity_id: ${weather_entity}
    attribute: pressure
    internal: true
  
  - platform: homeassistant
    id: wind_bearing
    entity_id: ${weather_entity}
    attribute: wind_bearing
    internal: true

  # ── 3D Printer (BambuLab) — Numeric
  - platform: homeassistant
    id: print_progress
    entity_id: sensor.p1s_01p09c482900380_progression_de_l_impression
    internal: true
  - platform: homeassistant
    id: bed_temp
    entity_id: sensor.p1s_01p09c482900380_temperature_du_lit
    internal: true
  - platform: homeassistant
    id: bed_temp_set
    entity_id: number.p1s_01p09c482900380_temperature_cible_du_lit
    internal: true
  - platform: homeassistant
    id: nozzle_temp
    entity_id: sensor.p1s_01p09c482900380_temperature_de_la_buse
    internal: true
  - platform: homeassistant
    id: nozzle_temp_set
    entity_id: number.p1s_01p09c482900380_temperature_cible_de_la_buse
    internal: true

# =============================
# Text Sensors (states/strings)
# =============================
text_sensor:
  # ── Buttons (entity states)
  - platform: homeassistant
    id: button1_entity_color
    entity_id: $button1_entity
    internal: true
  - platform: homeassistant
    id: button2_entity_color
    entity_id: $button2_entity
    internal: true
  - platform: homeassistant
    id: button3_entity_color
    entity_id: $button3_entity
    internal: true
  - platform: homeassistant
    id: button4_entity_color
    entity_id: $button4_entity
    internal: true
  - platform: homeassistant
    id: button5_entity_color
    entity_id: $button5_entity
    internal: true
  - platform: homeassistant
    id: button6_entity_color
    entity_id: $button6_entity
    internal: true
  - platform: homeassistant
    id: button7_entity_color
    entity_id: $button7_entity
    internal: true
  # ── Weather — State
  - platform: homeassistant
    id: weather_state
    name: "Current Weather Icon"
    entity_id: $weather_entity
    internal: true

  # ── Weather Alerts (Météo-France)
  - platform: homeassistant
    id: weather_alert
    entity_id: sensor.71_weather_alert
    internal: true
  - platform: homeassistant
    id: alert_vent
    entity_id: sensor.71_weather_alert
    attribute: Vent violent
    internal: true
  - platform: homeassistant
    id: alert_pluie
    entity_id: sensor.71_weather_alert
    attribute: Pluie-inondation
    internal: true
  - platform: homeassistant
    id: alert_orages
    entity_id: sensor.71_weather_alert
    attribute: Orages
    internal: true
  - platform: homeassistant
    id: alert_neige
    entity_id: sensor.71_weather_alert
    attribute: Neige-verglas
    internal: true
  - platform: homeassistant
    id: alert_inondation
    entity_id: sensor.71_weather_alert
    attribute: Inondation
    internal: true
  
  # ── Sun times (rise/set)
  - platform: homeassistant
    id: sunrise_time
    entity_id: sun.sun
    attribute: next_rising
    internal: true
  - platform: homeassistant
    id: sunset_time
    entity_id: sun.sun
    attribute: next_setting
    internal: true
  
  # ── Rain forecast (Météo-France)
  #     Raw attribute 1_hour_forecast parsed on the display lambda
  - platform: homeassistant
    id: next_rain_forecast_data
    entity_id: sensor.macon_next_rain
    attribute: 1_hour_forecast
    internal: true

  # ── 3D Printer (BambuLab) — Text
  - platform: homeassistant
    id: print_status
    entity_id: sensor.p1s_01p09c482900380_etat_de_l_impression
    internal: true
  - platform: homeassistant
    id: time_remaining
    entity_id: sensor.p1s_01p09c482900380_temps_restant
    internal: true
  - platform: homeassistant
    id: end_time
    entity_id: sensor.datefin_print
    internal: true
  - platform: homeassistant
    id: current_file
    entity_id: sensor.p1s_01p09c482900380_ficher_g_code
    internal: true
