# Home Assistant Sensors Integration
# Imports sensor data from Home Assistant entities

# Numeric Sensors (Temperature, Humidity, Weather Probabilities)
sensor:
  - platform: homeassistant
    id: temp_int
    entity_id: $internal_temp_sensor
    internal: true
  - platform: homeassistant
    id: hum_int
    entity_id: $internal_humidity_sensor
    internal: true
  - platform: homeassistant
    id: int2_temp
    entity_id: $int2_temp_sensor
    internal: true
  - platform: homeassistant
    id: int2_hum
    entity_id: $int2_humidity_sensor
    internal: true
  - platform: homeassistant
    id: temp_ext
    entity_id: $outside_temp_sensor
    internal: true
  - platform: homeassistant
    id: rainchance
    entity_id: $rain_chance
    internal: true
  - platform: homeassistant
    id: snowchance
    entity_id: $snow_chance
    internal: true
  - platform: homeassistant
    id: freezechance
    entity_id: $freeze_chance
    internal: true

  # Weather - Wind speed from weather entity attribute
  - platform: homeassistant
    id: wind_speed
    entity_id: ${weather_entity}
    attribute: wind_speed
    internal: true

  # BambuLab Printer (numeric sensors)
  - platform: homeassistant
    id: print_progress
    entity_id: sensor.p1s_01p09c482900380_progression_de_l_impression
    internal: true
  - platform: homeassistant
    id: bed_temp
    entity_id: sensor.p1s_01p09c482900380_temperature_du_lit
    internal: true
  - platform: homeassistant
    id: bed_temp_set
    entity_id: number.p1s_01p09c482900380_temperature_cible_du_lit
    internal: true
  - platform: homeassistant
    id: nozzle_temp
    entity_id: sensor.p1s_01p09c482900380_temperature_de_la_buse
    internal: true
  - platform: homeassistant
    id: nozzle_temp_set
    entity_id: number.p1s_01p09c482900380_temperature_cible_de_la_buse
    internal: true

# Text Sensors (Entity States)
text_sensor:
  - platform: homeassistant
    id: button1_entity_color
    entity_id: $button1_entity
    internal: true
  - platform: homeassistant
    id: button2_entity_color
    entity_id: $button2_entity
    internal: true
  - platform: homeassistant
    id: button3_entity_color
    entity_id: $button3_entity
    internal: true
  - platform: homeassistant
    id: button4_entity_color
    entity_id: $button4_entity
    internal: true
  - platform: homeassistant
    id: button5_entity_color
    entity_id: $button5_entity
    internal: true
  - platform: homeassistant
    id: button6_entity_color
    entity_id: $button6_entity
    internal: true
  - platform: homeassistant
    id: weather_state
    name: "Current Weather Icon"
    entity_id: $weather_entity
    internal: true

  # Weather Alert
  - platform: homeassistant
    id: weather_alert
    entity_id: sensor.71_weather_alert
    internal: true
  - platform: homeassistant
    id: alert_vent
    entity_id: sensor.71_weather_alert
    attribute: Vent violent
    internal: true
  - platform: homeassistant
    id: alert_pluie
    entity_id: sensor.71_weather_alert
    attribute: Pluie-inondation
    internal: true
  - platform: homeassistant
    id: alert_orages
    entity_id: sensor.71_weather_alert
    attribute: Orages
    internal: true
  - platform: homeassistant
    id: alert_neige
    entity_id: sensor.71_weather_alert
    attribute: Neige-verglas
    internal: true
  - platform: homeassistant
    id: alert_inondation
    entity_id: sensor.71_weather_alert
    attribute: Inondation
    internal: true

  # BambuLab Printer (text sensors)
  - platform: homeassistant
    id: print_status
    entity_id: sensor.p1s_01p09c482900380_etat_de_l_impression
    internal: true
  - platform: homeassistant
    id: time_remaining
    entity_id: sensor.p1s_01p09c482900380_temps_restant
    internal: true
  - platform: homeassistant
    id: end_time
    entity_id: sensor.datefin_print
    internal: true
  - platform: homeassistant
    id: current_file
    entity_id: sensor.p1s_01p09c482900380_ficher_g_code
    internal: true
