# =============================================================================
# Home Assistant Sensors Integration
# =============================================================================
# Imports sensor data from Home Assistant entities.
# All entity IDs are configured in substitutions.yaml.
# =============================================================================

# ─────────────────────────────────────────────────────────────────────────────
# Numeric Sensors (measurements)
# ─────────────────────────────────────────────────────────────────────────────
sensor:
  # ── Sensor Bloc 1 (Indoor)
  - platform: homeassistant
    id: sensor_bloc1_temp
    entity_id: $sensor_bloc1_temp_entity
    internal: true
  - platform: homeassistant
    id: sensor_bloc1_hum
    entity_id: $sensor_bloc1_hum_entity
    internal: true

  # ── Sensor Bloc 2 (Indoor)
  - platform: homeassistant
    id: sensor_bloc2_temp
    entity_id: $sensor_bloc2_temp_entity
    internal: true
  - platform: homeassistant
    id: sensor_bloc2_hum
    entity_id: $sensor_bloc2_hum_entity
    internal: true

  # ── Sensor Bloc 3 (Optional - leave entity empty to disable)
  - platform: homeassistant
    id: sensor_bloc3_temp
    entity_id: $sensor_bloc3_temp_entity
    internal: true
  - platform: homeassistant
    id: sensor_bloc3_hum
    entity_id: $sensor_bloc3_hum_entity
    internal: true

  # ── Sensor Bloc 4 (Optional - leave entity empty to disable)
  - platform: homeassistant
    id: sensor_bloc4_temp
    entity_id: $sensor_bloc4_temp_entity
    internal: true
  - platform: homeassistant
    id: sensor_bloc4_hum
    entity_id: $sensor_bloc4_hum_entity
    internal: true

  # ── Outdoor Temperature
  - platform: homeassistant
    id: temp_ext
    entity_id: $outside_temp_entity
    internal: true

  # ── Weather — Probabilities
  - platform: homeassistant
    id: rainchance
    entity_id: $rain_chance_entity
    internal: true
  - platform: homeassistant
    id: snowchance
    entity_id: $snow_chance_entity
    internal: true
  - platform: homeassistant
    id: freezechance
    entity_id: $freeze_chance_entity
    internal: true

  # ── Weather — Attributes from weather entity
  - platform: homeassistant
    id: wind_speed
    entity_id: ${weather_entity}
    attribute: wind_speed
    internal: true
  - platform: homeassistant
    id: humidity_ext
    entity_id: ${weather_entity}
    attribute: humidity
    internal: true
  - platform: homeassistant
    id: pressure
    entity_id: ${weather_entity}
    attribute: pressure
    internal: true
  - platform: homeassistant
    id: wind_bearing
    entity_id: ${weather_entity}
    attribute: wind_bearing
    internal: true

  # ── 3D Printer — Numeric
  - platform: homeassistant
    id: print_progress
    entity_id: $printer_progress_entity
    internal: true
  - platform: homeassistant
    id: bed_temp
    entity_id: $printer_bed_temp_entity
    internal: true
  - platform: homeassistant
    id: bed_temp_set
    entity_id: $printer_bed_target_entity
    internal: true
  - platform: homeassistant
    id: nozzle_temp
    entity_id: $printer_nozzle_temp_entity
    internal: true
  - platform: homeassistant
    id: nozzle_temp_set
    entity_id: $printer_nozzle_target_entity
    internal: true

# ─────────────────────────────────────────────────────────────────────────────
# Text Sensors (states/strings)
# ─────────────────────────────────────────────────────────────────────────────
text_sensor:
  # ── Button States (for icon colors)
  - platform: homeassistant
    id: btn1_state
    entity_id: $btn1_entity
    internal: true
  - platform: homeassistant
    id: btn2_state
    entity_id: $btn2_entity
    internal: true
  - platform: homeassistant
    id: btn3_state
    entity_id: $btn3_entity
    internal: true
  - platform: homeassistant
    id: btn4_state
    entity_id: $btn4_entity
    internal: true
  - platform: homeassistant
    id: btn5_state
    entity_id: $btn5_entity
    internal: true
  - platform: homeassistant
    id: btn6_state
    entity_id: $btn6_entity
    internal: true
  - platform: homeassistant
    id: btn7_state
    entity_id: $btn7_entity
    internal: true

  # ── Weather — State
  - platform: homeassistant
    id: weather_state
    name: "Current Weather Icon"
    entity_id: $weather_entity
    internal: true

  # ── Weather Alerts (Météo-France)
  - platform: homeassistant
    id: weather_alert
    entity_id: $weather_alert_entity
    internal: true
  - platform: homeassistant
    id: alert_vent
    entity_id: $weather_alert_entity
    attribute: Vent violent
    internal: true
  - platform: homeassistant
    id: alert_pluie
    entity_id: $weather_alert_entity
    attribute: Pluie-inondation
    internal: true
  - platform: homeassistant
    id: alert_orages
    entity_id: $weather_alert_entity
    attribute: Orages
    internal: true
  - platform: homeassistant
    id: alert_neige
    entity_id: $weather_alert_entity
    attribute: Neige-verglas
    internal: true
  - platform: homeassistant
    id: alert_inondation
    entity_id: $weather_alert_entity
    attribute: Inondation
    internal: true

  # ── Sun times (rise/set)
  - platform: homeassistant
    id: sunrise_time
    entity_id: sun.sun
    attribute: next_rising
    internal: true
  - platform: homeassistant
    id: sunset_time
    entity_id: sun.sun
    attribute: next_setting
    internal: true

  # ── Rain forecast (Météo-France)
  - platform: homeassistant
    id: next_rain_forecast_data
    entity_id: $rain_forecast_entity
    attribute: 1_hour_forecast
    internal: true

  # ── 3D Printer — Text
  - platform: homeassistant
    id: print_status
    entity_id: $printer_status_entity
    internal: true
  - platform: homeassistant
    id: time_remaining
    entity_id: $printer_time_remaining_entity
    internal: true
  - platform: homeassistant
    id: end_time
    entity_id: $printer_end_time_entity
    internal: true
  - platform: homeassistant
    id: current_file
    entity_id: $printer_gcode_entity
    internal: true
  - platform: homeassistant
    id: printer_switch_state
    entity_id: $printer_switch_entity
    internal: true
